spring:
  thymeleaf:
    mode: HTML

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog2?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: Do!ng123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

comment.avatar: /images/avatar.png



